### ISSUE TITLE
Load weights

### ISSUE THREAD

**Issue by mlopezantequera** [kwotsin/TensorFlow-Xception#2]
It'd be nice to be able to load the weights [provided](https://github.com/fchollet/deep-learning-models/blob/master/xception.py#L46) in the keras implementation by @fchollet.

Are you already working on this? Otherwise I can start doing so.

**Comment by kwotsin** [comment]
Actually I'm not sure if there's a way to convert the keras weights to tensorflow .ckpt files. Is this conversion possible? It would be great if you can provide such a conversion and share it! :D

**Comment by HiKapok** [comment]
I have convert that weights in keras to tensorflow, see [here](https://github.com/HiKapok/Xception_Tensorflow) if you still interested in.
